// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: HXT.proto
#ifndef GRPC_HXT_2eproto__INCLUDED
#define GRPC_HXT_2eproto__INCLUDED

#include "HXT.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace HXT {

class RPC final {
 public:
  static constexpr char const* service_full_name() {
    return "HXT.RPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Setup
    std::unique_ptr< ::grpc::ClientWriterInterface< ::HXT::SetupRequestMessage>> setup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::HXT::SetupRequestMessage>>(setupRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::HXT::SetupRequestMessage>> Asyncsetup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::HXT::SetupRequestMessage>>(AsyncsetupRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::HXT::SetupRequestMessage>> PrepareAsyncsetup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::HXT::SetupRequestMessage>>(PrepareAsyncsetupRaw(context, response, cq));
    }
    // Search
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>> consearch(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>>(consearchRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>> Asyncconsearch(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>>(AsyncconsearchRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>> PrepareAsyncconsearch(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>>(PrepareAsyncconsearchRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Setup
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void setup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::HXT::SetupRequestMessage>* reactor) = 0;
      #else
      virtual void setup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::experimental::ClientWriteReactor< ::HXT::SetupRequestMessage>* reactor) = 0;
      #endif
      // Search
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void consearch(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::HXT::SearchRequestMessage,::HXT::SearchReply>* reactor) = 0;
      #else
      virtual void consearch(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::HXT::SearchRequestMessage,::HXT::SearchReply>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientWriterInterface< ::HXT::SetupRequestMessage>* setupRaw(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::HXT::SetupRequestMessage>* AsyncsetupRaw(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::HXT::SetupRequestMessage>* PrepareAsyncsetupRaw(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* consearchRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* AsyncconsearchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* PrepareAsyncconsearchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::HXT::SetupRequestMessage>> setup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::HXT::SetupRequestMessage>>(setupRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::HXT::SetupRequestMessage>> Asyncsetup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::HXT::SetupRequestMessage>>(AsyncsetupRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::HXT::SetupRequestMessage>> PrepareAsyncsetup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::HXT::SetupRequestMessage>>(PrepareAsyncsetupRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>> consearch(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>>(consearchRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>> Asyncconsearch(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>>(AsyncconsearchRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>> PrepareAsyncconsearch(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>>(PrepareAsyncconsearchRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void setup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::ClientWriteReactor< ::HXT::SetupRequestMessage>* reactor) override;
      #else
      void setup(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::experimental::ClientWriteReactor< ::HXT::SetupRequestMessage>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void consearch(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::HXT::SearchRequestMessage,::HXT::SearchReply>* reactor) override;
      #else
      void consearch(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::HXT::SearchRequestMessage,::HXT::SearchReply>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientWriter< ::HXT::SetupRequestMessage>* setupRaw(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response) override;
    ::grpc::ClientAsyncWriter< ::HXT::SetupRequestMessage>* AsyncsetupRaw(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::HXT::SetupRequestMessage>* PrepareAsyncsetupRaw(::grpc::ClientContext* context, ::HXT::ExecuteStatus* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* consearchRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* AsyncconsearchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* PrepareAsyncconsearchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_setup_;
    const ::grpc::internal::RpcMethod rpcmethod_consearch_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Setup
    virtual ::grpc::Status setup(::grpc::ServerContext* context, ::grpc::ServerReader< ::HXT::SetupRequestMessage>* reader, ::HXT::ExecuteStatus* response);
    // Search
    virtual ::grpc::Status consearch(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::HXT::SetupRequestMessage>* /*reader*/, ::HXT::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsetup(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::HXT::ExecuteStatus, ::HXT::SetupRequestMessage>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_consearch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_consearch() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_consearch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status consearch(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestconsearch(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_setup<WithAsyncMethod_consearch<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_setup() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackClientStreamingHandler< ::HXT::SetupRequestMessage, ::HXT::ExecuteStatus>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::HXT::ExecuteStatus* response) { return this->setup(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::HXT::SetupRequestMessage>* /*reader*/, ::HXT::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::HXT::SetupRequestMessage>* setup(
      ::grpc::CallbackServerContext* /*context*/, ::HXT::ExecuteStatus* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::HXT::SetupRequestMessage>* setup(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::HXT::ExecuteStatus* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_consearch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_consearch() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackBidiHandler< ::HXT::SearchRequestMessage, ::HXT::SearchReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->consearch(context); }));
    }
    ~ExperimentalWithCallbackMethod_consearch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status consearch(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* consearch(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::HXT::SearchRequestMessage, ::HXT::SearchReply>* consearch(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_setup<ExperimentalWithCallbackMethod_consearch<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_setup<ExperimentalWithCallbackMethod_consearch<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::HXT::SetupRequestMessage>* /*reader*/, ::HXT::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_consearch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_consearch() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_consearch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status consearch(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setup() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::HXT::SetupRequestMessage>* /*reader*/, ::HXT::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsetup(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_consearch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_consearch() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_consearch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status consearch(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestconsearch(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_setup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_setup() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->setup(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_setup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setup(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::HXT::SetupRequestMessage>* /*reader*/, ::HXT::ExecuteStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* setup(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* setup(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_consearch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_consearch() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->consearch(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_consearch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status consearch(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::HXT::SearchReply, ::HXT::SearchRequestMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* consearch(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* consearch(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace HXT


#endif  // GRPC_HXT_2eproto__INCLUDED
